version: '3'
services:
  dev:
    image: kviver/sdk:nrf5-2019-07-18
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - .:/project
      - .docker/cache/cargo_registry:/home/developer/.cargo/registry
      - .docker/fixuid.yml:/etc/fixuid/config.yml
      - /dev/bus/usb:/dev/bus/usb
    working_dir: "/project/stm32f103cbt"
  dev-server:
    build: ./.docker/images/dev-server
    command: "bash -c 'npm ci && npm run start'"
    ports:
      - "3001:3001"
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    tty: true
    stdin_open: true
#    TODO setup cache from npm
    volumes:
      - .:/project
      - .docker/fixuid.yml:/etc/fixuid/config.yml
    working_dir: "/project/dev-server/server"
  dev-ui:
    build: ./.docker/images/dev-server
    command: "bash -c 'npm ci && npm run start'"
    ports:
      - "3000:3000"
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    tty: true
    stdin_open: true
#    TODO setup cache from npm
    volumes:
      - .:/project
      - .docker/fixuid.yml:/etc/fixuid/config.yml
    working_dir: "/project/dev-server/ui"
